### ISSUE TITLE
更新docker镜像后数据被清空，希望能够挂载数据卷

### ISSUE THREAD

**Issue by Carlos920** [TakcC/PHP-EPG-Docker-Server#7]
当前镜像即使将 htdocs 挂载出来，更新镜像后依旧会被重置，所有数据都需要重新配置

**Comment by TakcC** [comment]
我回头重写一个docker compose吧，之前没搞定运行权限，给删了。

**Comment by Carlos920** [comment]
还有个问题是当前版本的manage.php里，定时任务日志与数据库更新日志都是空的，得进管理数据库中查看日志
![IMG_20240801_205214.jpg](https://github.com/user-attachments/assets/af77eed8-66d0-4d8b-8c08-8f73274e476a)

![IMG_20240801_205246.jpg](https://github.com/user-attachments/assets/31d9be74-f478-468e-b2ee-79f3e13dc653)

**Comment by TakcC** [comment]
这么奇怪？是加载不出来么？你是拉镜像还是自己的环境？

**Comment by Carlos920** [comment]
> 这么奇怪？是加载不出来么？你是拉镜像还是自己的环境？

拉的镜像
```
php-epg:
    image: taksss/php-epg:latest
    container_name: php-epg
    #volumes:
    #  - ./php-epg:/htdocs/epg
    ports:
      - 8000:80
    restart: always
```
